baseURL = 'https://tsaidondon.github.io'
languageCode = 'zh-tw'
defaultContentLanguage = "zh-tw"
title = "Dondon Tsai"
theme = 'FixIt'
hasCJKLanguage = true
summaryLength = 50
withSiteTitle = false
[params]
  [params.author]
    name = "Dondon Tsai"
  [params.cookieconsent]
    enable = false
  [params.page]
    authorAvatar = false
    wordCount = false
    readingTime = false    
    pageStyle = "narrow"
    license = ""
    [params.page.share]
      enable = false
      Twitter = false
      Facebook = false
  [params.home.posts]
      enable = true
      paginate = 6

 [params.home.profile]
      enable = true
      gravatarEmail = ""
      avatarURL = "/avatar.png"
      avatarMenu = ""
      title = ""
      subtitle = ""
      typeit = false
      social = false
  [params.footer]
    enable = true
    custom = ""
    copyright = true
    author = true
    since = ""
    gov = ""
    icp = ""
    license = ""
    [params.footer.powered]
      enable = true
      hugoLogo = false
      themeLogo = false

[menu]
  [[menu.main]]
    identifier = "tags"
    parent = ""
    pre = ""
    post = ""
    name = "標籤"
    url = "/tags/"
    title = ""
    weight = 3
    [menu.main.params]
      icon = "fa-solid fa-tags"
  [[menu.main]]
    identifier = "about"
    parent = ""
    pre = ""
    post = ""
    name = "關於"
    url = "/about/"
    title = ""
    weight = 5
    # FixIt 0.2.14 | NEW add user-defined content to menu items
    [menu.main.params]
      icon = "fa-solid fa-link"
